blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [
     path('create/', BlogCreateView.as_view(), name='create'),
     path('', BlogListView.as_view(), name='blog_list'),
     path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
     path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
     path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='shop')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое')
    photo = models.ImageField(upload_to='blog/', verbose_name='Изображение', **NULLABLE)
    created_at = models.DateField(auto_now=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликован')
    count_views = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

blog/views.py
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'is_published', 'photo')
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'is_published', 'photo')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
        return super().form_valid(form)

    def get_success_url(self):
        from django.urls import reverse
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить статью "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a href="{% url 'blog:blog_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load mymedia %}

{% block content %}


<h1 align="center"> {{ object }} </h1>

<div class="card px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center" style="width: 24rem;">
  <div class="card-body">
    <img class="card-img-top" src="{{ object.photo | media_filter }}">
    <p class="card-text"> {{ object.content }}</p>
    <p class="card-text">{{ object.created_at }}</p>
    <p class="card-text"> Просмотров: {{ object.count_views }}</p>
    <div class="d-grid gap-2 mx-auto">
    <a href="{% url 'blog:blog_list' %}" class="w-100 btn btn-lg btn-outline-secondary"> Назад </a>
    </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" class="form-floating" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button Type="submit" class="btn btn-success">
                            {% if object %}
                            Изменить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                        <a href="{% url 'blog:blog_list' %}" class="btn btn-warning" style="margin-top: 0px;">
                        Вернуться назад </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}


{% block title %} Новостной блог {% endblock %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h4 class="display-4">Интернет-магазин электроники</h4>
    <p class="lead"> Откройте двери в мир инноваций с нашим интернет-магазином! </p >

    <h2>Новостной блог</h2>
</div>
<div class="col-12 mb-5 text-center">
    <a class="w-20 btn btn-lg btn-outline-success" href="{% url 'blog:create' %}"> Добавить статью </a>
</div>
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %}

        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 align="center" class="my-0 fw-normal"><strong>{{ object | truncatechars:40 }} </strong>
                    </h4>
                </div>
                <div class="card-body">
                    <ul align="center" class="list-unstyled mt-3 mb-4">
                        <li>{{ object.content | truncatechars:100 }}</li>
                        <li>{{ object.created_at }}</li>
                        <li>Просмотров: {{ object.count_views }}</li>
                    </ul>
                    <a href="{% url 'blog:view' object.pk %}" class="w-100 btn btn-lg btn-outline-primary">
                        Подробнее </a>
                    <a href="{% url 'blog:edit' object.pk %}" class="w-100 btn btn-lg btn-outline-success">
                        Редактировать статью </a>
                    <a href="{% url 'blog:delete' object.pk %}" class="w-100 btn btn-lg btn-outline-dark"> Удалить
                        статью </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}