blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [
     path('create/', BlogCreateView.as_view(), name='create'),
     path('', BlogListView.as_view(), name='blog_list'),
     path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
     path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
     path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path

from catalog.views import ProductListView, ProductView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView

app_name = 'shop'

urlpatterns = [
    path('', ProductListView.as_view(), name='list_products'),
    path('contacts/', ProductView.as_view(), name='contacts'),
    path('view/<int:pk>/', ProductDetailView.as_view(), name='product_info'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='edit_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='shop')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return f'Category({self.name})'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    product_name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    image = models.ImageField(upload_to='products/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена', **NULLABLE)
    created_at = models.DateField(verbose_name='Дата создания', **NULLABLE)
    updated_at = models.DateField(verbose_name='Дата изменения', **NULLABLE)

    def __str__(self):
        return f'Product({self.product_name})'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    number_version = models.IntegerField(verbose_name="Номер версии")
    name = models.CharField(verbose_name="Название версии")
    is_active = models.BooleanField(default=False, verbose_name="Активная версия")

    def __str__(self):
        return f'{self.number_version}'

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"

catalog/forms.py
from django import forms
from django.forms.fields import BooleanField
from catalog.models import Product, Version


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('created_at', 'updated_at',)

    def clean_product_name(self):
        cleaned_data = self.cleaned_data['product_name']
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for word in forbidden_words:
            if word in cleaned_data:
                raise forms.ValidationError("В названии товара были обнаружены один или несколько недопустимых "
                                            "слов.")
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for word in forbidden_words:
            if word in cleaned_data:
                raise forms.ValidationError("В описании товара были обнаружены один или несколько недопустимых "
                                            "слов.")
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Version


class ProductView(View):
    def get(self, request):
        return render(request, 'catalog/contacts.html')

    def post(self, request):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(f'You have new message from {name} {phone} ({email}): {message}')
        return render(request, 'catalog/contacts.html')


class ProductListView(ListView):
    model = Product

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        products = Product.objects.all()

        for product in products:
            versions = Version.objects.filter(product=product)
            active_versions = versions.filter(is_active=True)
            if active_versions:
                product.active_version = active_versions.last().name
            else:
                product.active_version = 'Нет активной версии'

        context_data['object_list'] = products
        return context_data


class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        product = self.get_object()
        versions = Version.objects.filter(product=product)
        active_version = versions.filter(is_active=True).last()

        if active_version:
            product.active_version = active_version.name
        else:
            product.active_version = 'Нет активной версии'

        context_data['object'] = product
        return context_data


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('shop:list_products')


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('shop:list_products')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shop:list_products')

catalog/templates/catalog/base.html
<!doctype html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block title %} {% endblock %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
{% block menu %}

{% include "catalog/menu.html" %}

{% endblock %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h4 class="display-4">Интернет-магазин электроники</h4>
    <p class="lead"> Откройте двери в мир инноваций с нашим интернет-магазином! </p >
{% endblock %}
</body>

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            Мир инноваций с нами
            <small class="d-block mb-3 text-muted">&copy; 2024</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории товаров</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Бытовая техника</a></li>
                <li><a class="text-muted" href="#">Ноутбуки и планшеты</a></li>
                <li><a class="text-muted" href="#">Телефоны и смарт-часы</a></li>
                <li><a class="text-muted" href="#">Наушники и аудиотехника</a></li>
                <li><a class="text-muted" href="#">Телевизоры и видеотехника</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block title %} Контакты {% endblock %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h4 class="display-4">Интернет-магазин электроники</h4>
    <p class="lead"> Откройте двери в мир инноваций с нашим интернет-магазином! </p >

    <h2>Контактная информация</h2>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна:</td>
                            <td>Российская Федерация</td>
                        </tr>
                        <tr>
                            <td class="w-25">Регион:</td>
                            <td>Краснодарский край</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес:</td>
                            <td>г. Неизвестный, ул. Примерная, д. 123.</td>
                        </tr>
                        <tr>
                            <td class="w-25">Email:</td>
                            <td>info@example.com</td>
                        </tr>
                        <tr>
                            <td class="w-25">Телефон:</td>
                            <td>+7(123)456-78-90</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h5 align="center" class="my-0 font-weight-normal">Свяжитесь с нами</h5>
                </div>
                <div class="card-body">
                    <h6 align="center">Форма обратной связи</h6>
                    <form method="post">
                        {% csrf_token %}
                        <label for="name">Имя:</label><br>
                        <input type="text" name="name"  class="form-control" id="name" placeholder="Введите имя" required><br>
                        <label for="email">Контактный телефон:</label><br>
                        <input type="phone" name="phone" class="form-control" id="phone" placeholder="Введите номер телефона" required><br>
                        <label for="email">Email:</label><br>
                        <input type="email" name="email" class="form-control" id="email" placeholder="Введите email" required><br>
                        <label for="message">Сообщение:</label><br>
                        <textarea name="message" class="form-control" id="message" rows="4" placeholder="Введите сообщение" required></textarea><br>
                        <button type="submit">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load mediapath %}

{% block title %} Главная {% endblock %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h4 class="display-4">Интернет-магазин электроники</h4>
    <p class="lead"> Откройте двери в мир инноваций с нашим интернет-магазином! </<p >

    <h2>Популярные товары</h2>
</div>
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 align="center" class="my-0 fw-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <img class="card-img-top" src="{% media_tag object.image %}">
                    <h1 align="center" class="card-title pricing-card-title">{{ object.price }} ₽</h1>
                    <ul align="center" class="list-unstyled mt-3 mb-4">
                        <li> Категория: {{ object.category.name }}</li>
                        <li>{{ object.description | truncatechars:100 }}</li>
                    </ul>
                    <a href="{% url 'shop:product_info' object.pk %}" class="w-100 btn btn-lg btn-outline-primary"> О
                        товаре </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/menu.html
{% block menu %}

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal"> Мир инноваций с нами </h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:blog_list' %}">Блог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Хотите удалить товар: "{{ object.product_name }}"? </p>
                        <button Type="submit" class="btn btn-danger"> Подтвердить </button>
                    </form>
                    <a href="{% url 'shop:list_products' %}" class="btn btn-warning" style="margin-top: 10px;"> Отмена </a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load mediapath %}
{% block title %} Информация о товаре {% endblock %}

{% block content %}


<h1 align="center"> {{ object.name }} </h1>

<div class="card px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center" style="width: 24rem;">
    <div class="card-body">
        <img class="card-img-top" src="{% media_tag object.image %}">
        <h5 class="card-title">{{ object.nomination | upper}}</h5>
        <p class="card-text">Описание: {{ object.description }}</p>
        <p class="card-text">Категория: {{ object.category.name }}</p>
        <p class="card-text">Дата создания: {{ object.created_at }}</p>
        <p class="card-text">Дата последнего изменения: {{ object.updated_at }}</p>
        <p class="card-text">Активная версия: {{ object.active_version }}</p>
        <div class="d-grid gap-2 mx-auto">
            <a href="#" class="btn btn-success"> Цена: {{object.price | floatformat:'0'}} ₽</a>
            <a href="{% url 'shop:list_products' %}" class="w-100 btn btn-lg btn-outline-secondary"> Назад </a>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="col-6">
            <h3> Создать товар </h3>
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button Type="submit" class="btn btn-success">
                        {% if object %}
                        Изменить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                    <a href="{% url 'shop:list_products' %}" class="btn btn-warning" style="margin-top: 0px;">
                        Вернуться назад </a>
                </div>
            </div>
        </div>
        <div class="col-6">
            <h3> Версии товара </h3>
            <div class="card">
                <div class="card-body">
                    {{formset.management_form }}
                    {% for form in formset.forms %}
                    {{form.as_p }}
                    {% if not forloop.last %}
                    <hr>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </form>
    {% endblock %}
</div>

catalog/templates/catalog/product_info.html
{% extends 'catalog/base.html' %}
{% load mediapath %}
{% block title %} Информация о товаре {% endblock %}

{% block content %}


<h1 align="center"> {{ object.name }} </h1>

<div class="card px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center" style="width: 24rem;">
    <div class="card-body">
        <img class="card-img-top" src="{% media_tag object.image %}">
        <h5 class="card-title">{{ object.nomination | upper}}</h5>
        <p class="card-text">Описание: {{ object.description }}</p>
        <p class="card-text">Категория: {{ object.category.name }}</p>
        <p class="card-text">Дата создания: {{ object.created_at }}</p>
        <p class="card-text">Дата последнего изменения: {{ object.updated_at }}</p>
        <div class="d-grid gap-2 mx-auto">
            <a href="#" class="btn btn-success"> Цена: {{object.price | floatformat:'0'}} ₽</a>
            <a href="{% url 'shop:home' %}" class="w-100 btn btn-lg btn-outline-secondary"> Назад </a>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load mediapath %}

{% block title %} Главная {% endblock %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h4 class="display-4">Интернет-магазин электроники</h4>
    <p class="lead"> Откройте двери в мир инноваций с нашим интернет-магазином! </p>

    <h2>Популярные товары</h2>
</div>
<div class="col-12 mb-5 text-center">
    <a class="w-20 btn btn-lg btn-outline-primary" href="{% url 'shop:create_product' %}"> Добавить
        товар </a>
</div>
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 align="center" class="my-0 fw-normal">{{ object.product_name }}</h4>
                </div>
                <div class="card-body">
                    <img class="card-img-top" src="{% media_tag object.image %}">
                    <h1 align="center" class="card-title pricing-card-title">Цена: {{ object.price }} ₽</h1>
                    <ul align="center" class="list-unstyled mt-3 mb-4">
                        <li> Категория: {{ object.category.name }}</li>
                        <li>{{ object.description | truncatechars:100 }}</li>
                        <li> Активная версия: {{ object.active_version }}</li>
                    </ul>
                    <a href="{% url 'shop:product_info' object.pk %}" class="w-100 btn btn-lg btn-outline-primary"> О
                        товаре </a>
                    <a href="{% url 'shop:edit_product' object.pk %}" class="w-100 btn btn-lg btn-outline-success">
                        Редактировать товар </a>
                    <a href="{% url 'shop:delete_product' object.pk %}" class="w-100 btn btn-lg btn-outline-danger">
                        Удалить товар </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}